services:
  postgres:
    image: postgres:16.3-alpine
    volumes:
      - ./docker/data/database:/var/lib/postgresql/data
      - ./docker/build/database/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posts
      POSTGRES_USER: user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d posts"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # imgproxy:
  #   image: darthsim/imgproxy:v3
  #   env_file: .env.imgproxy
  #   ports:
  #     - "8088:8080"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4:latest
    user: root
    ports:
      - 5050:80
    depends_on:
      - postgres
    volumes:
      - ./docker/build/pgadmin:/var/lib/pgadmin/storage/user_example.com
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password

  admin:
    build:
      context: .
      target: dev
      args:
        VITE_API_URL: "http://localhost:802/admin"
      dockerfile: ./docker/build/admin/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/admin:/app

  # back:
  #   build:
  #     context: .
  #     target: dev        
  #     dockerfile: ./docker/build/backend/Dockerfile
  #   ports:
  #     - "3333:3333"
  #   volumes:
  #     - ./apps/backend:/app