export const Icons = {
  "arrow-up" : require("../../../assets/icons/arrow-up.png"),
  "bell" : require("../../../assets/icons/bell.png"),
  "bookmark-filled" : require("../../../assets/icons/bookmark-filled.png"),
  "check" : require("../../../assets/icons/check.png"),
  "chevron-down" : require("../../../assets/icons/chevron-down.png"),
  "chevron-left" : require("../../../assets/icons/chevron-left.png"),
  "chevron-right" : require("../../../assets/icons/chevron-right.png"),
  "chevron-up" : require("../../../assets/icons/chevron-up.png"),
  "coin" : require("../../../assets/icons/coin.png"),
  "comment.delete" : require("../../../assets/icons/comment/delete.png"),
  "comment.reply-user" : require("../../../assets/icons/comment/reply-user.png"),
  "comment.reply" : require("../../../assets/icons/comment/reply.png"),
  "cross" : require("../../../assets/icons/cross.png"),
  "document" : require("../../../assets/icons/document.png"),
  "dots" : require("../../../assets/icons/dots.png"),
  "flashlight" : require("../../../assets/icons/flashlight.png"),
  "language" : require("../../../assets/icons/language.png"),
  "logout" : require("../../../assets/icons/logout.png"),
  "menu.delete" : require("../../../assets/icons/menu/delete.png"),
  "menu.edit" : require("../../../assets/icons/menu/edit.png"),
  "menu.share" : require("../../../assets/icons/menu/share.png"),
  "no-polls" : require("../../../assets/icons/no-polls.png"),
  "post.comments" : require("../../../assets/icons/post/comments.png"),
  "post.dislike-filled" : require("../../../assets/icons/post/dislike-filled.png"),
  "post.dislike" : require("../../../assets/icons/post/dislike.png"),
  "post.like-filled" : require("../../../assets/icons/post/like-filled.png"),
  "post.like" : require("../../../assets/icons/post/like.png"),
  "post.rapid" : require("../../../assets/icons/post/rapid.png"),
  "post.share" : require("../../../assets/icons/post/share.png"),
  "profile-placeholder" : require("../../../assets/icons/profile-placeholder.png"),
  "settings" : require("../../../assets/icons/settings.png"),
  "tabs.posts" : require("../../../assets/icons/tabs/posts.png"),
  "tabs.profile" : require("../../../assets/icons/tabs/profile.png"),
};
export type IconsType = keyof typeof Icons;
   